---
strategy: ablation
baseline:
  ignore_determiners: false
  mix_fasttext_wn2vec: 1.0
  similarity_measure: cosine
  idf_weight: 0.6
  similarity_falloff: 0.93
  pos_weighting: 0.46
  pos_mismatch_penalty: 0.77
  similarity_threshold: 0.73
  mismatch_length_penalty: 1
  submatch_weight: 0.24
  bidirectional: false
parameters:
  - name: ignore_determiners
    type: boolean
  - name: mix_fasttext_wn2vec
    type: uniform
    low: 0
    high: 1
  - name: pos_weighting
    type: uniform
    low: 0
    high: 1
  - name: pos_mismatch_penalty
    type: uniform
    low: 0
    high: 1
  - name: mismatch_length_penalty
    type: int
    low: -1
    high: 10
  - name: submatch_weight
    type: uniform
    low: 0
    high: 5
  - name: idf_weight
    type: uniform
    low: 0
    high: 1
  - name: bidirectional
    type: boolean
  - name: similarity_threshold
    type: uniform
    low: 0
    high: 1
  - name: similarity_falloff
    type: uniform
    low: 0
    high: 1
  - name: similarity_measure
    type: categorical
    choices:
      - cosine
      - nicdm
      - apsynp
